# Generated by Django 5.2.1 on 2025-06-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='sms_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='sms_code_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
