# Generated by Django 5.2.1 on 2025-06-18 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_perfilusuario_sms_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisosRRHH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solo_lectura', models.BooleanField(default=False)),
                ('puede_eliminar', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_rrhh', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
