# Generated by Django 5.2.1 on 2025-06-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_remove_permisosrrhh_solo_lectura'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisosrrhh',
            name='puede_crear',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permisosrrhh',
            name='puede_editar',
            field=models.BooleanField(default=False),
        ),
    ]
