# Generated by Django 5.1.7 on 2025-04-17 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('porcentaje_cotizacion', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FONASA', 'Fonasa'), ('ISAPRE', 'Isapre')], max_length=10)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('porcentaje_cotizacion', models.DecimalField(decimal_places=2, default=7.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SeguroCesantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_trabajador', models.DecimalField(decimal_places=2, default=0.6, max_digits=5)),
                ('porcentaje_empleador', models.DecimalField(decimal_places=2, default=2.4, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.cargo')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('sueldo_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personal.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('sueldo_bruto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sueldo_imponible', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ingresos_no_imponibles', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento_afp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento_salud', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento_cesantia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento_inasistencias', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_horas_extras', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('otros_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sueldo_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('documento', models.FileField(blank=True, null=True, upload_to='liquidaciones/')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='PermisoAusencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.CharField(max_length=255)),
                ('aprobado', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('presente', models.BooleanField(default=True)),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, default=8, max_digits=4)),
                ('horas_extras', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='DatosPrevisionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.afp')),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personal.empleado')),
                ('salud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.salud')),
                ('seguro_cesantia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.segurocesantia')),
            ],
        ),
        migrations.CreateModel(
            name='OtroDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_descuento', to='personal.liquidacion')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.tipodescuento')),
            ],
        ),
    ]
