# Generated by Django 5.1.7 on 2025-05-15 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_empleador_parametrosistema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='empleador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.empleador'),
        ),
    ]
