# Generated by Django 5.1.7 on 2025-05-21 07:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_empleado_empleador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PalabraClave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(choices=[('habilidad', 'Habilidad'), ('certificacion', 'Certificación'), ('area', 'Área')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PalabraDesconocida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=100, unique=True)),
                ('fecha_detectada', models.DateTimeField(auto_now_add=True)),
                ('veces_detectada', models.PositiveIntegerField(default=1)),
                ('revisada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=50)),
                ('otros_nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('curriculum', models.FileField(blank=True, null=True, upload_to='postulantes/cv/')),
                ('estado', models.CharField(choices=[('postulado', 'Postulado'), ('entrevista', 'Entrevista'), ('evaluacion', 'Evaluación'), ('seleccionado', 'Seleccionado'), ('descartado', 'Descartado')], default='postulado', max_length=20)),
                ('fecha_postulacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('cargo_postulado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.cargo')),
                ('etiquetas', models.ManyToManyField(blank=True, to='personal.etiqueta')),
            ],
        ),
    ]
