# Generated by Django 5.1.7 on 2025-05-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_etiqueta_palabraclave_palabradesconocida_postulante'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='prioridad',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='postulante',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
