# Generated by Django 5.1.7 on 2025-05-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_empleado_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodescuento',
            name='controla_asistencia',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipodescuento',
            name='requiere_cotizaciones',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipodescuento',
            name='requiere_liquidacion',
            field=models.BooleanField(default=True),
        ),
    ]
