# Generated by Django 5.1.7 on 2025-05-28 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_tipodescuento_controla_asistencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipodescuento',
            name='controla_asistencia',
        ),
        migrations.RemoveField(
            model_name='tipodescuento',
            name='requiere_cotizaciones',
        ),
        migrations.RemoveField(
            model_name='tipodescuento',
            name='requiere_liquidacion',
        ),
    ]
