# Generated by Django 5.1.7 on 2025-05-28 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_remove_tipodescuento_controla_asistencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglasContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('requiere_cotizaciones', models.BooleanField(default=True)),
                ('controla_asistencia', models.BooleanField(default=True)),
                ('requiere_liquidacion', models.BooleanField(default=True)),
                ('genera_vacaciones', models.BooleanField(default=True)),
                ('afecta_antiguedad', models.BooleanField(default=True)),
                ('requiere_firma_digital', models.BooleanField(default=False)),
                ('aplica_seguro_invalidez', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='reglas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.reglascontrato'),
        ),
    ]
