# Generated by Django 5.1.7 on 2025-05-30 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_tipocontrato_alter_contrato_tipo_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='superior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.cargo'),
        ),
    ]
