# Generated by Django 5.1.7 on 2025-06-01 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0012_cargo_superior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='reglas',
        ),
        migrations.AddField(
            model_name='tipocontrato',
            name='reglas',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.reglascontrato'),
        ),
    ]
