# Generated by Django 5.1.7 on 2025-06-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0013_remove_contrato_reglas_tipocontrato_reglas'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
