# Generated by Django 5.1.7 on 2025-06-04 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0015_horario_remove_registroasistencia_empleado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupohorario',
            name='horarios',
        ),
        migrations.AddField(
            model_name='horario',
            name='grupo',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='personal.grupohorario'),
            preserve_default=False,
        ),
    ]
