# Generated by Django 5.1.7 on 2025-06-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0016_remove_grupohorario_horarios_horario_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='dia_semana',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='hora_entrada',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='hora_salida',
        ),
        migrations.AddField(
            model_name='grupohorario',
            name='horarios',
            field=models.ManyToManyField(related_name='grupos', to='personal.horario'),
        ),
        migrations.AddField(
            model_name='horario',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], default='Lunes', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horario',
            name='hora_fin',
            field=models.TimeField(default='22:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horario',
            name='hora_inicio',
            field=models.TimeField(default='11:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grupohorario',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
