# Generated by Django 5.1.7 on 2025-06-05 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0017_remove_horario_dia_semana_remove_horario_grupo_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="horario",
            old_name="hora_inicio",
            new_name="hora_entrada",
        ),
        migrations.RenameField(
            model_name="horario",
            old_name="hora_fin",
            new_name="hora_salida",
        ),
        migrations.RenameField(
            model_name="horario",
            old_name="dia",
            new_name="dia_semana",
        ),
    ]
