# Generated by Django 5.1.7 on 2025-06-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0018_auto_20250605_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioempleado',
            name='es_personalizado',
            field=models.BooleanField(default=False),
        ),
    ]
